import {
  siBurpsuite,
  siCloudflare,
  siDiscorddotjs,
  siDocker,
  siExpo,
  siGit,
  siHeroui,
  siJavascript,
  siKalilinux,
  siLinux,
  siMetasploit,
  siMysql,
  siNextdotjs,
  siNodedotjs,
  siOwasp,
  siReact,
  siSupabase,
  siTailwindcss,
  siTypescript,
  siVercel,
  siWireshark,
} from "simple-icons"

export const brands = {
  nextjs: siNextdotjs,
  react: siReact,
  typescript: siTypescript,
  javascript: siJavascript,
  tailwind: siTailwindcss,
  heroui: siHeroui,
  node: siNodedotjs,
  supabase: siSupabase,
  mysql: siMysql,
  vercel: siVercel,
  expo: siExpo,
  discordjs: siDiscorddotjs,
  git: siGit,
  docker: siDocker,
  linux: siLinux,
  kali: siKalilinux,
  burp: siBurpsuite,
  metasploit: siMetasploit,
  owasp: siOwasp,
  wireshark: siWireshark,
  cloudflare: siCloudflare,
}

export type Brand = keyof typeof brands
